export function getDocText(fields) {
  let t = `VoxSana — Approved Medical Document\n${new Date().toLocaleString('en-GB')}\n${'─'.repeat(50)}\n\n`
  fields.forEach((f) => {
    t += `${f.label} [${f.sourceLabel ?? ''}]:\n${f.value ?? ''}\n\n`
  })
  return t + `${'─'.repeat(50)}\nApproved by physician. Generated by VoxSana.`
}

export function exportAs(format, fields) {
  const text = getDocText(fields)
  if (format === 'clipboard') {
    return navigator.clipboard.writeText(text)
  }
  if (format === 'txt') {
    const b = new Blob([text], { type: 'text/plain' })
    const u = URL.createObjectURL(b)
    const a = document.createElement('a')
    a.href = u
    a.download = `voxsana_${new Date().toISOString().slice(0, 10)}.txt`
    a.click()
    URL.revokeObjectURL(u)
    return Promise.resolve()
  }
  if (format === 'pdf') {
    const win = window.open('', '_blank')
    win.document.write(
      `<html><head><title>VoxSana Document</title><style>body{font-family:Georgia,serif;font-size:12px;line-height:1.6;max-width:700px;margin:40px auto;color:#111}pre{white-space:pre-wrap;word-wrap:break-word}</style></head><body><pre>${text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')}</pre></body></html>`
    )
    win.document.close()
    win.focus()
    setTimeout(() => { win.print(); win.close() }, 300)
    return Promise.resolve()
  }
}
